env:
  browser: true
  es2021: true
extends:
  - "plugin:@next/next/recommended"
  - "standard-with-typescript"
rules:
  space-before-function-paren: [warn, 0]
  comma-dangle: [warn, 0]
  semi: [warn, always]
  quotes: [warn, double]
  "@typescript-eslint/quotes": [warn, double]
  "@typescript-eslint/semi": [warn, always]
  "@typescript-eslint/space-before-function-paren": [warn, never]
  "@typescript-eslint/member-delimiter-style": off
ignorePatterns:
  - "next-env.d.ts"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  project: ["./tsconfig.json"]
plugins:
  - "react"
settings:
  react:
    version: "detect"
