env:
  browser: true
  es2021: true
extends:
  - "plugin:@next/next/recommended"
  - "standard-with-typescript"
rules:
  space-before-function-paren:
    - warn
    - anonymous: "never"
      named: "never"
      asyncArrow: "always"
  comma-dangle: [warn, never]
  semi: [warn, always]
  quotes: [warn, double]
  multiline-ternary: 0
  "@typescript-eslint/quotes": [warn, double]
  "@typescript-eslint/semi": [warn, always]
  "@typescript-eslint/space-before-function-paren":
    - warn
    - anonymous: "never"
      named: "never"
      asyncArrow: "always"
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/restrict-template-expressions": off
  "@typescript-eslint/no-unused-vars": warn
ignorePatterns:
  - "next-env.d.ts"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  project: ["./tsconfig.json"]
plugins:
  - "react"
settings:
  react:
    version: "detect"
