env:
  browser: true
  es2021: true
extends:
  - 'plugin:@next/next/recommended'
  - 'standard-with-typescript'
rules:
  space-before-function-paren: 0
  comma-dangle: 0
  semi:
    - error
    - always
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: ['./tsconfig.json']
plugins:
  - 'react'
settings:
  react:
    version: 'detect'
