env:
  browser: true
  es2021: true
extends:
  - 'plugin:@next/next/recommended'
  - 'standard-with-typescript'
overrides: []
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: ['./tsconfig.json']
plugins:
  - 'react'
settings:
  react:
    version: 'detect'
