env:
  browser: true
  es2021: true
extends:
  - 'plugin:@next/next/recommended'
  - 'standard-with-typescript'
rules:
  '@typescript-eslint/space-before-function-paren': 0
  '@typescript-eslint/comma-dangle': 0
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: ['./tsconfig.json']
plugins:
  - 'react'
settings:
  react:
    version: 'detect'
